name: Publish to JFrog
on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish to JFrog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
        with:
          ruby-version: '3.1'

      - name: Install dependencies
        run: bundle install

      - name: Run test cases
        run: rspec

      - name: Build production bundle
        run: gem build tippr_deluxe.gemspec

      - name: Publish
        run: find * -name 'tippr_deluxe-*' | gem push