name: Publish to JFrog
on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish to JFrog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
        with:
          ruby-version: '2.7.6'
      - name: Check version changes
        uses: EndBug/version-check@v2
        id: check
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Version update detected
        if: steps.check.outputs.changed == 'true'
        run: 'echo "Version change found! New version: ${{ steps.check.outputs.version }} (${{ steps.check.outputs.type }})"'

      - name: Install dependencies
        if: steps.check.outputs.changed == 'true'
        run: bundle install

      - name: Run test cases
        if: steps.check.outputs.changed == 'true'
        run: rspec

      - name: Build production bundle
        if: steps.check.outputs.changed == 'true'
        run: gem build seismic_universal_auth.gemspec

      - name: Publish
        if: steps.check.outputs.changed == 'true'
        run: find * -name 'tippr_deluxe-*' | gem push