name: Publish to JFrog
on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish to JFrog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
        with:
          ruby-version: '3.1'

      - name: Check version changes
        uses: dentarg/gem-compare@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        id: check

      - name: Version update detected
        if: steps.check.outputs.changed == 'true'
        run: 'echo "Version change found! New version: ${{ steps.check.outputs.version }} (${{ steps.check.outputs.type }})"'

      - name: Install dependencies
        if: steps.check.outputs.changed == 'true'
        run: bundle install

      - name: Run test cases
        if: steps.check.outputs.changed == 'true'
        run: rspec

      - name: Build production bundle
        if: steps.check.outputs.changed == 'true'
        run: gem build tippr_deluxe.gemspec

      - name: Publish
        if: steps.check.outputs.changed == 'true'
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem build *.gemspec
          gem push *.gem
        env:
          GEM_HOST_API_KEY: "${{secrets.GEM_HOST_API_KEY}}"