name: Version Forget-Me-Not

on:
  push:
    branches:
      - main # Change if your default branch is different
    types: [opened, synchronize]
permissions:
  contents: read
  statuses: write
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: simplybusiness/version-forget-me-not@v2.1.0
        env:
          ACCESS_TOKEN: ${{ secrets.GEM_HOST_API_KEY }}
          # Change to the file path where you keep the Gem's version.
          # It is usually `lib/<gem name>/version.rb` or in the gemspec file.
          VERSION_FILE_PATH: "lib/tippr_deluxe/version.rb"